### ISSUE TITLE
Helm release name must be airflow

### ISSUE THREAD

**Issue by sdanbury** [BrechtDeVlieger/airflow-kube-helm#3]
I came across your repo and gave it a go with minikube.

I changed the values file to use the `apache/airflow:latest` image and then ran:

```
$ helm install .
```

I got the following error:

```
$ helm install .
Error: release manageable-peacock failed: Deployment.apps "manageable-peacock-scheduler" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "airflow-dags", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "airflow-dags"]
```

Versions:
```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alistardust** [comment]
you should run the install from a directory higher than the helm chart itself and do something like `helm install ./airflow [flags]`

**Comment by sdanbury** [comment]
That isn't the issue, it should work the same way whether I am in the same directory as the chart or in another directory.

The issue is that the chart hard-codes the volumeMount to look for a volume called `airflow-dags`, but the volume is created with a name that is tied to the helm release name: `{{ template "airflow.fullname" . }}-dags`.

The fix is to change the chart to look for the volume name the same way, i.e. using `{{ template "airflow.fullname" . }}-dags` everywhere.
