### ISSUE TITLE
CrashLoop on Webserver and Scheduler

### ISSUE THREAD

**Issue by abishekh** [BrechtDeVlieger/airflow-kube-helm#6]
Hi,
First up, thank-you for putting this repository together, it is really helpful to get started with airflow and k8 quickly.
I've setup the git-sync-readwritemany version with NFS and an AWS hosted Postgres database, the web server and scheduler initialize and come up correctly and display a 'Running' status for 2-3 minutes but then keep crashing. I'm unable to access the webserver via port-forward either. 
I'm assuming that my troubles might be linked to this part in the readme:

> It can take a while before you can access the webserver.
> The scheduler and webserver usually try to connect to postgres before the database is ready,
> which results in connection timeouts.
> You can close the webserver and scheduler pods when the database is available to speed up the first deployment. 

I'm unsure what to make of it. Did you mean that the webserver and scheduler need to be brought-up sequentially ? or that the replicas need to be scaled down until some condition has been reached ? Or something else ..?

Here is a screenshot of the logs I'm seeing on the webserver and scheduler (similar logs on both):
![2019-06-04-Screenshot](https://user-images.githubusercontent.com/489699/58887792-e457ce00-86ab-11e9-8fb4-f50cb13361ce.png)

**Comment by jpmolinamatute** [comment]
According to this [thread](https://github.com/helm/charts/issues/15828#issuecomment-520385001) in the upstream repo, you need to build/push your own airflow docker image

**Comment by abishekh** [comment]
Yea I got around the problem. I believe it was an issue with the Postgres endpoint not being configured correctly. Everything works great now !
